version: '3'
services:
  activemq:
    image: solita/harja-activemq:5.15.9
    environment:
      - "TZ=Europe/Helsinki"
    container_name: activemq
    ports:
      - "127.0.0.1:61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "127.0.0.1:8161:8161"   # web    localhost:8161/admin/queues.jsp (admin:admin)
  harja-app:
    image: solita/harja-app:latest
    depends_on:
      - "harjadb"
    stdin_open: true
    ports:
      - "3000-3001:3000" # web ports
      - "4005-4006:4005" # REPL ports
    tty: true
    links:
      - harjadb
    environment:
      - "TZ=Europe/Helsinki"
    env_file:
      - .docker_compose_env
    command: bash /opt/odota-possu-ja-kaynnista-harja.sh
  harjadb:
    image: solita/harjadb:centos-12-compose
    stdin_open: true
    tty: true
    environment:
      - "TZ=Europe/Helsinki"
    env_file:
      - .docker_compose_env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
        - ./tietokanta:/var/lib/pgsql/harja/tietokanta