version: 2
jobs:
  build:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest
      - name: harjadb

    steps:
      - run: |
          bash sisus.bash back $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
