version: 2
jobs:
  build:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest

    steps:
      - run: |
          cd /tmp
          bash sisus.bash test+phantom $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
