version: 2
jobs:
  front-testit:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest

    steps:
      - run: |
          cd /tmp
          bash sisus.bash phantom $CIRCLE_BRANCH

  back-testit:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest

    steps:
      - run: |
          cd /tmp
          bash sisus.bash test $CIRCLE_BRANCH
  # T채nne voisi alkaa siirtelem채채n integraatiotestej채
  integraatio-testit:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest
      - image: solita/harja-activemq:5.15.9
        environment:
          TCP_PORT: 61617
          UI_PORT: 8162
        auth:
          username: solitaharja
          password: $DOCKER_HUB_SALASANA

    steps:
      - run: |
          cd /tmp
          bash sisus.bash integraatio $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_test:
    jobs:
      - back-testit
      - integraatio-testit
      - front-testit
