version: 2
jobs:
  front-testit:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest

    steps:
      - run: |
          cd /tmp
          bash sisus.bash phantom $CIRCLE_BRANCH

  back-testit:
    docker:
      - image: solita/harja-testit:latest # eka image = "primary container"
      - image: solita/harjadb:latest

    steps:
      - run: |
          cd /tmp
          bash sisus.bash test $CIRCLE_BRANCH

  e2e-testit:
    docker:
      - image: cypress/base:6
      - image: solita/harja-testit:latest
        command: ["back", "$CIRCLE_BRANCH"]
      - image: solita/harjadb:latest
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - back-testit
      - front-testit
      - e2e-testit
