version: 2
jobs:
  build:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/harjadb:latest

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ .Branch }}-{{ checksum "harja/project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-{{ .Branch }}
          - v2-dependencies-

      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "harja/project.clj" }}
          paths:
            - ~/.m2

      # setup database
      - run:
          name: Check any running databases
          command: |
            pwd
            fuser -n tcp -v 5432

      - run: cd tietokanta && sh devdb_migrate.sh

      # run tests!
      - run: cd harja && lein test

      - run:
          name: Build Harja jar
          command: cd harja && lein uberjar

      - run:
          name: Configure build
          command: |
            mkdir /tmp/harja
            mv harja/target/harja-0.1-SNAPSHOT-standalone.jar /tmp/harja/harja.jar
            sed < asetukset.edn > /tmp/harja/asetukset.edn -e 's/:kehitysmoodi true/:kehitysmoodi true\n :sahke-headerit {"oletus-kaytto-oikeudet" {"oam_remote_user" "jvh" "oam_user_first_name" "Jarjestelman" "oam_user_last_name" "Valvoja" "oam_user_email" "jvh@example.com" "oam_groups" "Jarjestelmavastaava" "oam_organization" "Liikennevirasto"}}/'

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /tmp/harja
          # Must be relative path from root
          paths:
            - harja.jar
            - config.edn

  e2e-pr:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/harjadb:latest

    working_directory: ~/repo

    environment:
      ## this enables colors + fixes failing unit tests (they say)
      TERM: "xterm"
      LEIN_ROOT: "true"
      CYPRESS_BASE_URL: "http://localhost:3000"
      #DEBUG: "cypress*"

    steps:
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/harja

      # setup database
      - run: cd tietokanta && ./devdb_restart.sh

      - restore_cache:
          keys:
            - v2-npm-deps-

      - run:
          name: Install Cypress
          command: npm i cypress@1.x && $(npm bin)/cypress verify

      - save_cache:
          key: v2-npm-deps-
          paths:
            - node_modules

      - run:
          name: Run Harja app
          command: cd /tmp/harja && java -jar harja.jar
          background: true

      # Note: When running with chrome, it seems we cannot record a video. Only Electron browser can record a video.
      - run:
          name: Run smoke tests for pull request
          command: $(npm bin)/cypress run --browser chrome --record --spec cypress/integration/nakymien_avaus_spec.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - e2e-pr:
          requires:
            - build
