version: 2
jobs:
  build:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/harjadb:latest

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ .Branch }}-{{ checksum "harja/project.clj" }}
          - v2-dependencies-{{ .Branch }}
          - v2-dependencies-

      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "harja/project.clj" }}
          paths:
            - ~/.m2

      - run: cd tietokanta && mvn flyway:migrate && sh devdb_testidata.sh --localhost

      - run:
          name: Rakenna Harja jar
          command: lein do clean, deps, compile, cljsbuild once prod, less once, cljsbuild once laadunseuranta-min, uberjar

      - run:
          name: Konfiguroi buildi
          command: |
            mkdir /tmp/harja
            cp asetukset.edn cypress.json /tmp/harja/
            mv target/harja-0.0.1-SNAPSHOT-standalone.jar /tmp/harja/harja.jar

      - persist_to_workspace:
          root: /tmp/harja
          paths:
            - harja.jar
            - asetukset.edn
            - cypress.json

  unit-tests:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/harjadb:latest

    steps:
      - run:
          name: Aseta aikavyöhyke
          command: echo 'Europe/Helsinki' | sudo tee /etc/timezone

      - run:
          name: Aseta aikavyöhyke
          command: sudo dpkg-reconfigure --frontend noninteractive tzdata

      - run:
          name: Aja yksikkötestit ilman suorituskykytestejä
          command: lein test :no-perf

      - run:
          name: Aja Harjan front end -testit
          command: lein doo phantom test once

      - run:
          name: Aja mobiililaadunseurannan front end -testit
          command: lein doo phantom laadunseuranta-test once

  e2e-pr:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/harjadb:latest

    working_directory: ~/repo

    environment:
      TERM: "xterm"
      LEIN_ROOT: "true"
      CYPRESS_BASE_URL: "http://localhost:3000"
      #DEBUG: "cypress*"

    steps:
      - checkout

      - attach_workspace:
          at: /tmp/harja

      - run: cd tietokanta && mvn flyway:migrate && sh devdb_testidata.sh --localhost

      - restore_cache:
          keys:
            - v2-npm-deps-

      - run:
          name: Asenna Cypress
          command: npm i cypress@1.x && $(npm bin)/cypress verify

      - save_cache:
          key: v2-npm-deps-
          paths:
            - node_modules

      - run:
          name: Korjaa salasanat asetuksiin
          command: ls /tmp/harja && sed -i /tmp/harja/asetukset.edn -e 's/#=(slurp "[^"]*")/"xxxx"/g'

      - run:
          name: Aseta kehitysmoodi pois päältä
          command: ls /tmp/harja && sed -i /tmp/harja/asetukset.edn -e 's/:kehitysmoodi true/:kehitysmoodi false/'

      - run:
          name: Käynnistä Harja-sovellus
          command: cd /tmp/harja && env TZ=EET java -jar harja.jar
          background: true

      - run:
          name: Odota sovelluksen käynnistymistä
          command: for i in {1..10}; do curl http://localhost:3000 > /dev/null 2>&1 && break; echo wait/retry $i; sleep 5; done

      - run:
          name: Aja smoketestit pull requestille
          command: $(npm bin)/cypress run --browser chrome --spec cypress/integration/nakymien_avaus_spec.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      # Ota pois kommenteista ajaaksesi Cypress.io E2E-testit
      - e2e-pr:
          requires:
            - unit-tests
