version: '3'
services:
  phantom:
    image: harja-phantom-testit
    container_name: harja-phantom
    environment:
      - "TZ=Europe/Helsinki"
    volumes:
      - ..:/harja-src
    # ports:
    #   - "21:21"   # ssh
  harjadb:
    image: solita/harjadb
    container_name: harja-db
    environment:
      - "TZ=Europe/Helsinki"
    ports:
      - 5432:5432
    volumes:
        - ../tietokanta:/tietokanta
    command: |
         /bin/bash -c "
              echo Käynnistetään PostgreSQL
              service postgresql start

              cd tietokanta

              echo Odotetaan että PostgreSQL on käynnissä

              until mvn flyway:info &>/dev/null; do
                  echo Odotetaan että Flyway saa yhteyden kantaan...
                  sleep 0.5
              done

              echo Ajetaan migraatiot
              mvn flyway:migrate

              echo Ajetaan testidata harja-kantaan
              psql -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U harja harja -X -q -a -v ON_ERROR_STOP=1 --pset pager=off -f testidata.sql > /dev/null

              echo Luodaan harjatest_template tietokanta
              psql -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U harja harja -c \"CREATE DATABASE harjatest_template WITH TEMPLATE harja OWNER harjatest;\"

              echo Luodaan harjatest tietokantakanta
              psql -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U harja harja -c \"CREATE DATABASE harjatest WITH TEMPLATE harjatest_template OWNER harjatest;\"

              echo Tietokanta valmis käyttöön
              sleep 10000d"
